services:
  postgres:
    image: postgres:latest
    container_name: feedup
    ports:
      - "5432:5432"
    environment:
<<<<<<< HEAD
      POSTGRES_DB: feedup
=======
      POSTGRES_DB: feedup_teste2
>>>>>>> a72240516b0f14f390ea73b2319fcab8dc4eba57
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: